"""Tests for TPU kernel study empirical records and hardware evidence validation."""
import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
from scripts.tpu_kernels_records import hardware_evidence, source_hashes


def test_missing_tpu_hardware_cannot_pass(tmp_path):
    assert not hardware_evidence(tmp_path / "missing.json", {})["passed"]


def test_stale_tpu_hardware_cannot_pass(tmp_path):
    path = tmp_path / "metrics.json"
    path.write_text(json.dumps({"passed": True, "environment": {"source_sha256": {"src/kernels/pallas_afa.py": "old"}}}))
    assert not hardware_evidence(path, {"src/kernels/pallas_afa.py": "new"})["passed"]


def test_incomplete_tpu_inventory_cannot_pass(tmp_path):
    path = tmp_path / "metrics.json"
    path.write_text(
        json.dumps({
            "passed": True,
            "environment": {"source_sha256": {}},
            "device_count": 8,  # Only 8 chips instead of 16
            "process_count": 2,
            "devices": [{"kind": "TPU v4"}] * 8,
        })
    )
    assert not hardware_evidence(path, {})["passed"]


def test_committed_tpu_metrics_validates_cleanly():
    tpu_path = ROOT / "results/tpu_kernels/tpu/metrics.json"
    if not tpu_path.exists():
        pytest.skip("TPU evidence not yet produced")
    record = json.loads(tpu_path.read_text())
    hashes = source_hashes()
    if record.get("environment", {}).get("source_sha256") != hashes:
        pytest.skip("Committed TPU evidence is stale and must be regenerated by the aggregate verifier")
    res = hardware_evidence(tpu_path, hashes)
    assert res["passed"] is True, f"Committed TPU evidence failed validation: {res}"
    assert res["inventory_matches"] is True
    assert res["source_matches"] is True
