"""Tests for Pilot study empirical records and hardware evidence validation."""
import json
from pathlib import Path
import pytest

ROOT = Path(__file__).resolve().parents[1]
from scripts.pilot_records import hardware_evidence, source_hashes


def test_missing_tpu_hardware_cannot_pass(tmp_path):
    assert not hardware_evidence(tmp_path / "missing.json", {})["passed"]


def test_stale_tpu_hardware_cannot_pass(tmp_path):
    path = tmp_path / "metrics.json"
    path.write_text(json.dumps({
        "passed": True,
        "environment": {"source_sha256": {"src/model.py": "old"}},
        "pilot_pretraining": {"perplexity_ratio": 1.05, "nan_or_inf_count": 0, "loss_spike_count": 0, "peak_gradient_norm": 1.2, "throughput_ratio": 0.95},
        "ast_audit": {"passed": True},
    }))
    assert not hardware_evidence(path, {"src/model.py": "new"})["passed"]


def test_divergent_ppl_cannot_pass(tmp_path):
    path = tmp_path / "metrics.json"
    hashes = {"src/model.py": "abc"}
    path.write_text(json.dumps({
        "passed": True,
        "environment": {"source_sha256": hashes},
        "pilot_pretraining": {"perplexity_ratio": 1.45, "nan_or_inf_count": 0, "loss_spike_count": 0, "peak_gradient_norm": 1.2, "throughput_ratio": 0.95},
        "ast_audit": {"passed": True},
    }))
    assert not hardware_evidence(path, hashes)["passed"]


def test_short_pilot_cannot_pass(tmp_path):
    path = tmp_path / "metrics.json"
    hashes = {"src/model.py": "abc"}
    path.write_text(json.dumps({
        "environment": {"source_sha256": hashes},
        "device_count": 16,
        "total_steps": 200,
        "pilot_pretraining": {
            "perplexity_ratio": 1.0,
            "nan_or_inf_count": 0,
            "loss_spike_count": 0,
            "peak_gradient_norm": 1.0,
            "throughput_ratio": 1.0,
            "algebraic_results": {"total_steps": 200},
            "baseline_results": {"total_steps": 200},
        },
        "ast_audit": {"passed": True},
    }))
    result = hardware_evidence(path, hashes)
    assert result["passed"] is False
    assert result["required_steps"] == 100_000


def test_committed_tpu_metrics_validates_cleanly():
    tpu_path = ROOT / "results/pilot/tpu/metrics.json"
    if not tpu_path.exists():
        pytest.skip("TPU evidence not yet produced")
    record = json.loads(tpu_path.read_text())
    hashes = source_hashes()
    if record.get("environment", {}).get("source_sha256") != hashes:
        pytest.skip("Committed TPU evidence is stale and must be regenerated by the aggregate verifier")
    res = hardware_evidence(tpu_path, hashes)
    assert res["passed"] is True, f"Committed TPU evidence failed validation: {res}"
