"""Octic algebraic scoring loss and Pearson divergence.

Half precision reductions accumulate in float32; float64 remains float64 when
JAX enables it. Outputs and cotangents retain the input dtype."""

from functools import partial
from typing import Optional, Union

import jax
import jax.numpy as jnp

from src.primitives import _accumulate


def _rsqrt_eighth(p: jax.Array):
    """Evaluate p^{-1/8} via exactly three sequential hardware rsqrt operations."""
    z1 = jax.lax.rsqrt(p)
    z2 = jax.lax.rsqrt(z1)
    z3 = jax.lax.rsqrt(z2)
    return z3, z1


def _validate_loss_inputs(probabilities: jax.Array, gamma: float):
    if not jnp.issubdtype(probabilities.dtype, jnp.floating):
        raise TypeError("expected a floating point array for probabilities")
    if probabilities.ndim == 0 or probabilities.shape[-1] == 0:
        raise ValueError("probabilities must have a non-empty feature dimension")
    if not (0 < gamma < float("inf")):
        raise ValueError("gamma must be finite and strictly positive")


def _oace_forward(probabilities, targets, gamma):
    p = _accumulate(probabilities)
    targets = jnp.asarray(targets)

    if targets.ndim == p.ndim - 1 and targets.shape == p.shape[:-1]:
        # Integer class indices
        y = (jnp.arange(p.shape[-1]) == jnp.expand_dims(targets, -1)).astype(p.dtype)
        target_power_sum = jnp.ones(p.shape[:-1], dtype=p.dtype)
    elif targets.shape == p.shape:
        # One-hot or soft target distribution.  The safe value prevents the
        # y=0 boundary from evaluating 0 * rsqrt(0).
        y = targets.astype(p.dtype)
        safe_y = jnp.where(y > 0.0, y, 1.0)
        y_inverse_eighth, _ = _rsqrt_eighth(safe_y)
        target_power_sum = jnp.sum(y * y_inverse_eighth, axis=-1)
    else:
        raise ValueError(
            f"Targets shape {targets.shape} incompatible with probabilities shape {p.shape}"
        )

    z3, z1 = _rsqrt_eighth(p)
    # Proper power/Bregman score for alpha=1/8:
    #   8 sum(y p^-1/8) + 8/7 sum(p^7/8) - 64/7 sum(y^7/8).
    # The non-local correction is essential: the local term by itself has the
    # biased soft-target optimum p_i proportional to y_i^(8/9).
    loss = gamma * (
        8.0 * jnp.sum(y * z3, axis=-1)
        + (8.0 / 7.0) * jnp.sum(p * z3, axis=-1)
        - (64.0 / 7.0) * target_power_sum
    )
    return loss.astype(probabilities.dtype), (y, z1, z3)


def _oace_backward(gamma, cache, g):
    y, z1, z3 = cache
    upstream = jnp.asarray(g, dtype=z1.dtype)
    upstream = jnp.expand_dims(upstream, -1)
    # dL/dp_i = gamma * (p_i^-1/8 - y_i p_i^-9/8).
    dp = gamma * z3 * (1.0 - y * (z1 * z1)) * upstream
    return (dp.astype(g.dtype), None)


@partial(jax.custom_vjp, nondiff_argnums=(2,))
def _oace(probabilities, targets, gamma):
    return _oace_forward(probabilities, targets, gamma)[0]


_oace.defvjp(_oace_forward, _oace_backward)


@partial(jax.jit, static_argnames=("gamma", "reduction"))
def oace_loss(
    probabilities: jax.Array,
    targets: Union[jax.Array, int],
    gamma: float = 2.0,
    reduction: Optional[str] = "mean",
) -> jax.Array:
    """Strictly proper octic algebraic power score via hardware rsqrt.

    This is the Bregman score generated by the convex negative power entropy
    ``-sum(p**(7/8))``. Its non-local term gives the soft-target objective a
    stationary point at the target distribution.

    Args:
        probabilities: Strictly positive predicted probabilities on the simplex,
            shape (..., K).
        targets: Target class indices of shape (...) or soft labels of shape (..., K).
        gamma: Calibration scale factor (default: 2.0).
        reduction: Reduction method: 'mean', 'sum', or 'none' / None (default: 'mean').

    Returns:
        Loss array or scalar after reduction.
    """
    p = jnp.asarray(probabilities)
    _validate_loss_inputs(p, gamma)
    loss = _oace(p, targets, gamma)

    if reduction == "mean":
        return jnp.mean(loss)
    elif reduction == "sum":
        return jnp.sum(loss)
    elif reduction in ("none", None):
        return loss
    else:
        raise ValueError(f"Unknown reduction: {reduction}. Use 'mean', 'sum', or 'none'.")


def _pearson_forward(p, q):
    p_acc = _accumulate(p)
    q_acc = _accumulate(q)
    diff = p_acc - q_acc
    div = jnp.sum(diff * diff / q_acc, axis=-1)
    return div.astype(p.dtype), (p_acc, q_acc)


def _pearson_backward(cache, g):
    p, q = cache
    upstream = jnp.asarray(g, dtype=p.dtype)
    upstream = jnp.expand_dims(upstream, -1)
    dp = upstream * 2.0 * (p - q) / q
    dq = upstream * (1.0 - (p / q) * (p / q))
    return (dp.astype(g.dtype), dq.astype(g.dtype))


@jax.custom_vjp
def _pearson(p, q):
    return _pearson_forward(p, q)[0]


_pearson.defvjp(_pearson_forward, _pearson_backward)


@partial(jax.jit, static_argnames=("reduction",))
def pearson_divergence(
    p: jax.Array,
    q: jax.Array,
    reduction: Optional[str] = None,
) -> jax.Array:
    """Pearson chi^2 algebraic divergence D_A(p || q) = sum (p_i - q_i)^2 / q_i.

    Equivalently sum (p_i^2 / q_i) - 1 on the probability simplex.

    Args:
        p: Target / reference distribution, shape (..., K).
        q: Predicted distribution, shape (..., K).
        reduction: Optional reduction: None, 'none', 'mean', or 'sum'.
            If None or 'none', returns shape (...) summing over the last axis.

    Returns:
        Divergence array or scalar after reduction.
    """
    p_arr = jnp.asarray(p)
    q_arr = jnp.asarray(q)
    if not (jnp.issubdtype(p_arr.dtype, jnp.floating) and jnp.issubdtype(q_arr.dtype, jnp.floating)):
        raise TypeError("expected floating point arrays for p and q")
    if p_arr.shape != q_arr.shape:
        raise ValueError(f"Shape mismatch: p {p_arr.shape} vs q {q_arr.shape}")
    if p_arr.ndim == 0 or p_arr.shape[-1] == 0:
        raise ValueError("Inputs must have a non-empty feature dimension")

    div = _pearson(p_arr, q_arr)
    if reduction == "mean":
        return jnp.mean(div)
    elif reduction == "sum":
        return jnp.sum(div)
    elif reduction in ("none", None):
        return div
    else:
        raise ValueError(f"Unknown reduction: {reduction}. Use 'mean', 'sum', or 'none'.")
